# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: monitoring
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: kube-prometheus-stack
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 77.0.2
#     helm:
#       values: |
#         grafana:
#           ingress:
#             annotations:
#               alb.ingress.kubernetes.io/target-type: ip              
#             hosts: 
#               - grafana.example.com
#             enabled: true
#             ingressClassName: alb
#         prometheus: 
#           ingress:
#             hosts:
#               - prometheus.example.com
#             enabled: true
#             ingressClassName: alb
#           prometheusSpec:
#             storageSpec:
#                volumeClaimTemplate:
#                   spec:
#                      storageClassName: gp2
#                      accessModes: ["ReadWriteOnce"]
#                      resources:
#                        requests:
#                          storage: 5Gi
#                      selector: {}
#             nodeSelector:
#              disktype: appp-monitoring
#         alertmanager:
#           ingress:
#             hosts:
#               - alertmanager.example.com
#             enabled: true
#             ingressClassName: alb
#           alertmanagerSpec: 
#             nodeSelector:
#               disktype: app-monitoring  
#       releaseName: kube-prometheus-stack
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#       - ServerSideApply=true




